server:
  servlet:
    context-path: /
  port: 8050
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /**
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  rabbitmq:
    host: 192.168.1.28
    username: sohyun
    password: 5050
    port: 5672